Issue #199: Modify format of patch body per the Json Patch format.
Visual-Regression-Tracker/backend pull request #105
Opened 2021-02-23 04:51 UTC by suratdas

Implement https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/199 
Does not impact SDK.

2021-02-23 20:59 UTC, pashidlos commented on src/builds/builds.service.ts
> +  async update(id: string, modifyBuildDto: object): Promise<BuildDto> {
`Prisma.BuildUpdateInput` could be used as type

2021-02-23 21:01 UTC, pashidlos commented on src/builds/builds.controller.ts
> +      (patchObject as Operation[]).forEach(eachOpeartion => {
not sure how it's better then initial `ModifyBuildDto`

2021-02-23 21:02 UTC, pashidlos requested changes
@suratdas I appreciate your efforts but don't see this change solve any problem 
I like your previous implementation better as it has type checks 

is there any problem that we could address with new implementation?

2021-02-23 21:25 UTC, suratdas commented
@pashidlos I was trying to make it per the specification. I know it does not change any functionality. If it does not add too much value, we can completely descope this. Some of the reference materials (including spec) that talk about the proper implementation of PATCH are below.

https://williamdurand.fr/2014/02/14/please-do-not-patch-like-an-idiot/
https://www.baeldung.com/spring-rest-json-patch
https://tools.ietf.org/html/rfc6902
https://apisyouwonthate.com/blog/put-vs-patch-vs-json-patch

2021-02-24 07:21 UTC, pashidlos commented
@suratdas sorry, my bad 
as I understand it's the proposed way to update complex json objects
in our case it's handled by [Prisma](https://www.prisma.io/docs/concepts/components/prisma-client/crud#update) api that allows us provide only needed properties to update instead of full document replacement without loosing strict typing 
I'll postpone this change until we hit any restriction from Prisma side and we need external tool to overcome it

2021-02-24 07:21 UTC, closed without merging